### ISSUE TITLE
Troubleshooting documentation doesn't state that Player is discontinued

### ISSUE THREAD

**Issue by tristann21** [vinegarhq/vinegarhq.github.io#125]
![image](https://github.com/vinegarhq/vinegarhq.github.io/assets/154575581/b3fb8dab-27ad-40b7-87ac-a634bf8bc586)
![image](https://github.com/vinegarhq/vinegarhq.github.io/assets/154575581/f338d977-f3be-4de4-9ed7-dd347d758406)
![image](https://github.com/vinegarhq/vinegarhq.github.io/assets/154575581/83a810a7-cf75-4979-9c74-760da84d136b)

Atlas' information is outdated as well in the Discord because of this

![image](https://github.com/vinegarhq/vinegarhq.github.io/assets/154575581/9687f953-af85-4220-a0f2-d900c9697ab0)

**Comment by apprehensions** [comment]
The issues will stay because it is unknown if such issues are fixed or will remain an issue after Roblox enables Wine support. Such issues were made prior to it

**Comment by tristann21** [comment]
> The issues will stay because it is unknown if such issues are fixed or will remain an issue after Roblox enables Wine support. Such issues were made prior to it

that's kinda silly, you should at least have the banner at the top letting people know that Wine is being blocked. New users are becoming confused and trying fixes that do not work as of right now.

**Comment by apprehensions** [comment]
We cannot add a banner on every page. An equivalent is already in place present in the project's README document and the documentation's home page. It would be unnecessary.

**Comment by tristann21** [comment]
> We cannot add a banner on every page. An equivalent is already in place present in the project's README document and the documentation's home page. It would be unnecessary.

If you say so, not trying to be argumentative, but I'm also not asking you to put it on every page. When people are asked why Roblox Player isn't working, this is the page they're directed to first, and it would make helpdesk's lives a lot easier if it just told them rather than having to explain it to them or link them to a channel explaining it every time.

**Comment by apprehensions** [comment]
It would not change anything, since not everyone visits the documentation.

Feel free to contribute a change to the troubleshooting page.

**Comment by tristann21** [comment]
> It would not change anything, since not everyone visits the documentation.
> 
> Feel free to contribute a change to the troubleshooting page.

New to github, how may I contribute?

**Comment by apprehensions** [comment]
https://docs.github.com/en/get-started/exploring-projects-on-github/contributing-to-a-project
