### ISSUE TITLE
Roblox not opening

### ISSUE THREAD

**Issue by Magrelinhostili** [vinegarhq/vinegarhq.github.io#131]
When I start Sober, the screen remains black for a short period of time and then closes by itself. What can I do? ![Black screen for a short period of time](https://github.com/user-attachments/assets/b30317cb-3e45-4f4a-b418-99e0fe07da6d)

**Comment by jrelvas-ipc** [comment]
Hello. This issue tracker is for Vinegar's documentation website. 

Please make bug reports about Sober at https://github.com/vinegarhq/sober instead. Sober's maintainers watch the issue tracker there.
