### ISSUE TITLE
Sober not working on my steamdeck 

### ISSUE THREAD

**Issue by Rioninja4** [vinegarhq/vinegarhq.github.io#133]
whenever iopen the flatpak and try to install sober it says "Could not find 'app/org.vinegarhq.Sober/x86_64/' in 'sober'; please make sure it's available." and i have tried it again and again and reinstalling and it isnt working, help please😭🙏

**Comment by jrelvas-ipc** [comment]
Hello. This issue tracker is for Vinegar's documentation website. 

Please make bug reports about Sober at https://github.com/vinegarhq/sober instead. Sober's maintainers watch the issue tracker there.

Although there's an overlap, Vinegar and Sober contributors are not the same group.
