### ISSUE TITLE
Rendering Glitches

### ISSUE THREAD

**Issue by CatapultTV** [vinegarhq/vinegarhq.github.io#136]
**Rendering Glitches**

Not sure if it is a problem with Roblox Studios or maybe my computer, but there seems to be some problems when rendering objects as well as the scene and place, sometimes the icons in the windows also glitch out white and come back, here's how the scene looks inside of Studio
![image](https://github.com/user-attachments/assets/07291a63-7a1b-4d3d-a763-e0afcf3745d4)

Here's one for a car:
![image](https://github.com/user-attachments/assets/5ef63213-f318-43b9-9d6b-68b59a57f42e)

**Comment by CatapultTV** [comment]
As you can see in the 2nd picture (the car), the background fixed itself, however, if I zoomed out,add a new object or just move the camera, the lighting effect comes back and annoys me to death

**Comment by jrelvas-ipc** [comment]
Hello. This issue tracker is for Vinegar's documentation website.

Please make bug reports at https://github.com/vinegarhq/vinegar instead. Thank you.

**Comment by CatapultTV** [comment]
Sorry
